/**
 * Product API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductLite } from './productLite';


export interface CategoryResponse { 
    id: number;
    name: string;
    description?: string | null;
    products?: Array<ProductLite>;
}

