/**
 * Product API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CategoryLite } from './categoryLite';


export interface ProductResponse { 
    id: number;
    name: string;
    description?: string | null;
    price: number;
    stock: number;
    category_id?: number | null;
    category?: CategoryLite | null;
}

