/**
 * Product API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductLite { 
    id: number;
    name: string;
    description?: string | null;
    price: number;
    stock: number;
    category_id?: number | null;
}

