/**
 * Product API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductUpdate { 
    name?: string | null;
    description?: string | null;
    price?: number | null;
    stock?: number | null;
    category_id?: number | null;
}

